package paint;

/**
 * Ventana interna con contenido multimedia.
 * @author Montserrat Rodríguez Zamorano
 * @version 1.1
 */
public class VentanaMultimedia extends javax.swing.JInternalFrame {

    /**
     * Crea la nueva forma VentanaMultimedia
     */
    public VentanaMultimedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
