/**
 *
 * @author Montserrat Rodríguez Zamorano
 * @version 1.1
 */

package paint;

import graficos.Figura;
import graficos.Forma;
import iu.ColorRenderer;
import iu.Lienzo;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sm.sound.SMClipPlayer;
import sm.sound.SMSoundRecorder;
import graficos.TipoRelleno;
import iu.RellenoRenderer;
import graficos.TipoLinea;
import image.SepiaOp;
import image.UmbralizacionOp;
import image.disenioPropio2Op;
import image.disenioPropioOp;
import iu.LienzoImagen;
import iu.TipoLineaRenderer;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.Transparency;
import java.awt.color.ColorSpace;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.ColorConvertOp;
import java.awt.image.ColorModel;
import java.awt.image.ComponentColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.DataBuffer;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;
import sm.image.EqualizationOp;
import sm.image.KernelProducer;
import sm.image.LookupTableProducer;
import sm.image.TintOp;

public class VentanaPrincipal extends javax.swing.JFrame {
    private File temp = null;
    SMSoundRecorder recorder = null;
    SMClipPlayer player = null;
    private boolean grabando = false;
    BufferedImage imgSource;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        inicializarColores(colorTrazoCB);
        inicializarColores(colorRellenoCB);
        inicializarColores(degradado1CB);
        inicializarColores(degradado2CB);
        inicializarColores(colorTintadoCB);
        inicializarRelleno(tipoDegradadoCB);
        inicializarTipoLinea(tipoLineaCB);
 
        //sliders desactivados
        transparenciaSlider.setEnabled(false);
        tintadoSlider.setEnabled(false);
        
        //botones de sonido
        stopRecordBoton.setEnabled(false);
        pausaGrabacionBoton.setEnabled(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formasBG = new javax.swing.ButtonGroup();
        sonidoBG = new javax.swing.ButtonGroup();
        rotacionBG = new javax.swing.ButtonGroup();
        jButton4 = new javax.swing.JButton();
        barraFormasTB = new javax.swing.JToolBar();
        lineaBoton = new javax.swing.JToggleButton();
        rectanguloBoton = new javax.swing.JToggleButton();
        elipseBoton = new javax.swing.JToggleButton();
        FigurasCB = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        colorTrazoCB = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        rellenarBoton = new javax.swing.JToggleButton();
        colorRellenoCB = new javax.swing.JComboBox<>();
        tipoDegradadoCB = new javax.swing.JComboBox<>();
        degradado1CB = new javax.swing.JComboBox<>();
        degradado2CB = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        transparenciaBoton = new javax.swing.JToggleButton();
        transparenciaSlider = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        grosorSpinner = new javax.swing.JSpinner();
        tipoLineaCB = new javax.swing.JComboBox<>();
        alisarBoton = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        recordSonidoBoton = new javax.swing.JToggleButton();
        pausaGrabacionBoton = new javax.swing.JToggleButton();
        stopRecordBoton = new javax.swing.JToggleButton();
        listaAudiosCB = new javax.swing.JComboBox<>();
        reproducirSonidoBoton = new javax.swing.JToggleButton();
        pausaSonidoBoton = new javax.swing.JToggleButton();
        stopSonidoBoton = new javax.swing.JToggleButton();
        barraImagenesTB = new javax.swing.JToolBar();
        brilloSlider = new javax.swing.JSlider();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        contrasteBoton = new javax.swing.JButton();
        iluminarBoton = new javax.swing.JButton();
        oscurecerBoton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        sepiaBoton = new javax.swing.JButton();
        tintarBoton = new javax.swing.JToggleButton();
        colorTintadoCB = new javax.swing.JComboBox<>();
        tintadoSlider = new javax.swing.JSlider();
        ecualizacionBoton = new javax.swing.JButton();
        umbralizacionSlider = new javax.swing.JSlider();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        disminuirBoton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        rot90Boton = new javax.swing.JButton();
        rot180Boton = new javax.swing.JButton();
        rot270Boton = new javax.swing.JButton();
        giroLibreSlider = new javax.swing.JSlider();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        duplicarBoton = new javax.swing.JButton();
        negativoBoton = new javax.swing.JButton();
        relieveBoton = new javax.swing.JButton();
        emborronamientoBoton2 = new javax.swing.JButton();
        enfoqueBoton = new javax.swing.JButton();
        bandasBoton = new javax.swing.JButton();
        espacioColorCB = new javax.swing.JComboBox<>();
        disenioPropioBoton = new javax.swing.JButton();
        disenioPropio2Boton = new javax.swing.JButton();
        barraEstado = new javax.swing.JPanel();
        pixelLabel = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        archivoMenuBar = new javax.swing.JMenu();
        nuevoMenuItem = new javax.swing.JMenuItem();
        abrirMenuItem = new javax.swing.JMenuItem();
        guardarMenuItem = new javax.swing.JMenuItem();
        verMenuBar = new javax.swing.JMenu();
        verBarraEstadoCB = new javax.swing.JCheckBoxMenuItem();
        verBarraFormasCB = new javax.swing.JCheckBoxMenuItem();
        verBarraImagenCB = new javax.swing.JCheckBoxMenuItem();
        ayudaMenuBar = new javax.swing.JMenu();
        acercaMenuItem = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        barraFormasTB.setBorder(null);
        barraFormasTB.setRollover(true);
        barraFormasTB.setMaximumSize(new java.awt.Dimension(50, 30));
        barraFormasTB.setMinimumSize(new java.awt.Dimension(50, 30));
        barraFormasTB.setPreferredSize(new java.awt.Dimension(50, 30));

        formasBG.add(lineaBoton);
        lineaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        lineaBoton.setToolTipText("Línea");
        lineaBoton.setFocusable(false);
        lineaBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineaBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lineaBoton.addActionListener(formListener);
        barraFormasTB.add(lineaBoton);

        formasBG.add(rectanguloBoton);
        rectanguloBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        rectanguloBoton.setToolTipText("Rectángulo");
        rectanguloBoton.setFocusable(false);
        rectanguloBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectanguloBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectanguloBoton.addActionListener(formListener);
        barraFormasTB.add(rectanguloBoton);

        formasBG.add(elipseBoton);
        elipseBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        elipseBoton.setToolTipText("Elipse");
        elipseBoton.setFocusable(false);
        elipseBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipseBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipseBoton.addActionListener(formListener);
        barraFormasTB.add(elipseBoton);

        FigurasCB.setToolTipText("Figuras dibujadas");
        FigurasCB.setMaximumSize(new java.awt.Dimension(100, 32767));
        FigurasCB.setMinimumSize(new java.awt.Dimension(100, 27));
        FigurasCB.setPreferredSize(new java.awt.Dimension(100, 27));
        barraFormasTB.add(FigurasCB);
        barraFormasTB.add(jSeparator1);

        colorTrazoCB.setMaximumSize(new java.awt.Dimension(60, 32767));
        colorTrazoCB.setMinimumSize(new java.awt.Dimension(60, 27));
        colorTrazoCB.setPreferredSize(new java.awt.Dimension(60, 27));
        colorTrazoCB.addActionListener(formListener);
        barraFormasTB.add(colorTrazoCB);
        barraFormasTB.add(jSeparator7);

        rellenarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rellenar.png"))); // NOI18N
        rellenarBoton.setToolTipText("Relleno");
        rellenarBoton.setFocusable(false);
        rellenarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rellenarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rellenarBoton.addActionListener(formListener);
        barraFormasTB.add(rellenarBoton);

        colorRellenoCB.setToolTipText("Color relleno");
        colorRellenoCB.setMaximumSize(new java.awt.Dimension(60, 32767));
        colorRellenoCB.setMinimumSize(new java.awt.Dimension(60, 27));
        colorRellenoCB.setPreferredSize(new java.awt.Dimension(60, 27));
        colorRellenoCB.addActionListener(formListener);
        barraFormasTB.add(colorRellenoCB);

        tipoDegradadoCB.setToolTipText("Tipo relleno");
        tipoDegradadoCB.setMaximumSize(new java.awt.Dimension(150, 32767));
        tipoDegradadoCB.setMinimumSize(new java.awt.Dimension(150, 27));
        tipoDegradadoCB.setPreferredSize(new java.awt.Dimension(200, 27));
        tipoDegradadoCB.addActionListener(formListener);
        barraFormasTB.add(tipoDegradadoCB);

        degradado1CB.setToolTipText("Primer color degradado");
        degradado1CB.setMaximumSize(new java.awt.Dimension(60, 32767));
        degradado1CB.setMinimumSize(new java.awt.Dimension(60, 27));
        degradado1CB.setPreferredSize(new java.awt.Dimension(60, 27));
        degradado1CB.addActionListener(formListener);
        barraFormasTB.add(degradado1CB);

        degradado2CB.setToolTipText("Segundo color degradado");
        degradado2CB.setMaximumSize(new java.awt.Dimension(60, 32767));
        degradado2CB.setMinimumSize(new java.awt.Dimension(60, 27));
        degradado2CB.setPreferredSize(new java.awt.Dimension(60, 27));
        degradado2CB.addActionListener(formListener);
        barraFormasTB.add(degradado2CB);
        barraFormasTB.add(jSeparator6);

        transparenciaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/transparencia.png"))); // NOI18N
        transparenciaBoton.setToolTipText("Transparencia");
        transparenciaBoton.setFocusable(false);
        transparenciaBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transparenciaBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transparenciaBoton.addActionListener(formListener);
        barraFormasTB.add(transparenciaBoton);

        transparenciaSlider.setToolTipText("Nivel transparencia");
        transparenciaSlider.setValue(100);
        transparenciaSlider.setMaximumSize(new java.awt.Dimension(100, 29));
        transparenciaSlider.setMinimumSize(new java.awt.Dimension(100, 29));
        transparenciaSlider.setPreferredSize(new java.awt.Dimension(100, 29));
        transparenciaSlider.addChangeListener(formListener);
        barraFormasTB.add(transparenciaSlider);
        barraFormasTB.add(jSeparator2);

        grosorSpinner.setToolTipText("Grosor línea");
        grosorSpinner.setMaximumSize(new java.awt.Dimension(40, 32767));
        grosorSpinner.setMinimumSize(new java.awt.Dimension(40, 26));
        grosorSpinner.setPreferredSize(new java.awt.Dimension(40, 26));
        grosorSpinner.setValue(1);
        grosorSpinner.addChangeListener(formListener);
        barraFormasTB.add(grosorSpinner);

        tipoLineaCB.setMaximumSize(new java.awt.Dimension(100, 32767));
        tipoLineaCB.setMinimumSize(new java.awt.Dimension(100, 27));
        tipoLineaCB.setPreferredSize(new java.awt.Dimension(100, 27));
        tipoLineaCB.addActionListener(formListener);
        barraFormasTB.add(tipoLineaCB);

        alisarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/alisar.png"))); // NOI18N
        alisarBoton.setToolTipText("Alisado");
        alisarBoton.setFocusable(false);
        alisarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alisarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alisarBoton.addActionListener(formListener);
        barraFormasTB.add(alisarBoton);
        barraFormasTB.add(jSeparator3);

        sonidoBG.add(recordSonidoBoton);
        recordSonidoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/record24x24.png"))); // NOI18N
        recordSonidoBoton.setToolTipText("Iniciar grabación");
        recordSonidoBoton.setFocusable(false);
        recordSonidoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        recordSonidoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        recordSonidoBoton.addActionListener(formListener);
        barraFormasTB.add(recordSonidoBoton);

        sonidoBG.add(pausaGrabacionBoton);
        pausaGrabacionBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pausa24x24.png"))); // NOI18N
        pausaGrabacionBoton.setToolTipText("Pausar grabación");
        pausaGrabacionBoton.setFocusable(false);
        pausaGrabacionBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pausaGrabacionBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pausaGrabacionBoton.addActionListener(formListener);
        barraFormasTB.add(pausaGrabacionBoton);

        sonidoBG.add(stopRecordBoton);
        stopRecordBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stopRecord24x24.png"))); // NOI18N
        stopRecordBoton.setToolTipText("Finalizar grabación");
        stopRecordBoton.setFocusable(false);
        stopRecordBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopRecordBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stopRecordBoton.addActionListener(formListener);
        barraFormasTB.add(stopRecordBoton);

        listaAudiosCB.setToolTipText("Lista de sonidos");
        listaAudiosCB.setMaximumSize(new java.awt.Dimension(100, 32767));
        listaAudiosCB.setMinimumSize(new java.awt.Dimension(100, 27));
        barraFormasTB.add(listaAudiosCB);

        sonidoBG.add(reproducirSonidoBoton);
        reproducirSonidoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Play.png"))); // NOI18N
        reproducirSonidoBoton.setToolTipText("Play");
        reproducirSonidoBoton.setFocusable(false);
        reproducirSonidoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reproducirSonidoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reproducirSonidoBoton.addActionListener(formListener);
        barraFormasTB.add(reproducirSonidoBoton);

        sonidoBG.add(pausaSonidoBoton);
        pausaSonidoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Pausa.png"))); // NOI18N
        pausaSonidoBoton.setToolTipText("Pausa");
        pausaSonidoBoton.setFocusable(false);
        pausaSonidoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pausaSonidoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pausaSonidoBoton.addActionListener(formListener);
        barraFormasTB.add(pausaSonidoBoton);

        sonidoBG.add(stopSonidoBoton);
        stopSonidoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stop24x24.png"))); // NOI18N
        stopSonidoBoton.setToolTipText("Stop");
        stopSonidoBoton.setFocusable(false);
        stopSonidoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopSonidoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stopSonidoBoton.addActionListener(formListener);
        barraFormasTB.add(stopSonidoBoton);

        getContentPane().add(barraFormasTB, java.awt.BorderLayout.PAGE_START);

        barraImagenesTB.setBorder(null);
        barraImagenesTB.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barraImagenesTB.setRollover(true);
        barraImagenesTB.setMaximumSize(new java.awt.Dimension(40, 30));
        barraImagenesTB.setMinimumSize(new java.awt.Dimension(40, 30));
        barraImagenesTB.setPreferredSize(new java.awt.Dimension(45, 35));

        brilloSlider.setBackground(new java.awt.Color(204, 204, 204));
        brilloSlider.setMinimum(-100);
        brilloSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        brilloSlider.setToolTipText("Brillo");
        brilloSlider.setValue(0);
        brilloSlider.setMaximumSize(new java.awt.Dimension(29, 100));
        brilloSlider.setPreferredSize(new java.awt.Dimension(29, 80));
        brilloSlider.addChangeListener(formListener);
        brilloSlider.addFocusListener(formListener);
        barraImagenesTB.add(brilloSlider);
        barraImagenesTB.add(jSeparator4);

        contrasteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contraste.png"))); // NOI18N
        contrasteBoton.setToolTipText("Contraste");
        contrasteBoton.setFocusable(false);
        contrasteBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contrasteBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contrasteBoton.addActionListener(formListener);
        barraImagenesTB.add(contrasteBoton);

        iluminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iluminar.png"))); // NOI18N
        iluminarBoton.setToolTipText("Iluminar");
        iluminarBoton.setFocusable(false);
        iluminarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iluminarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iluminarBoton.addActionListener(formListener);
        barraImagenesTB.add(iluminarBoton);

        oscurecerBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/oscurecer.png"))); // NOI18N
        oscurecerBoton.setToolTipText("Oscurecer");
        oscurecerBoton.setFocusable(false);
        oscurecerBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        oscurecerBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        oscurecerBoton.addActionListener(formListener);
        barraImagenesTB.add(oscurecerBoton);
        barraImagenesTB.add(jSeparator5);

        sepiaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sepia.png"))); // NOI18N
        sepiaBoton.setToolTipText("Filtro sepia");
        sepiaBoton.setFocusable(false);
        sepiaBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sepiaBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sepiaBoton.addActionListener(formListener);
        barraImagenesTB.add(sepiaBoton);

        tintarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tintar.png"))); // NOI18N
        tintarBoton.setToolTipText("Tintado");
        tintarBoton.setFocusable(false);
        tintarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tintarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tintarBoton.addActionListener(formListener);
        barraImagenesTB.add(tintarBoton);

        colorTintadoCB.setToolTipText("Color tintado");
        colorTintadoCB.setMaximumSize(new java.awt.Dimension(60, 27));
        colorTintadoCB.setMinimumSize(new java.awt.Dimension(60, 27));
        colorTintadoCB.setPreferredSize(new java.awt.Dimension(60, 27));
        colorTintadoCB.addActionListener(formListener);
        barraImagenesTB.add(colorTintadoCB);

        tintadoSlider.setBackground(new java.awt.Color(204, 204, 204));
        tintadoSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        tintadoSlider.setToolTipText("Nivel de tintado");
        tintadoSlider.setMaximumSize(new java.awt.Dimension(29, 100));
        tintadoSlider.setPreferredSize(new java.awt.Dimension(29, 80));
        tintadoSlider.addChangeListener(formListener);
        tintadoSlider.addFocusListener(formListener);
        barraImagenesTB.add(tintadoSlider);

        ecualizacionBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ecualizar.png"))); // NOI18N
        ecualizacionBoton.setToolTipText("Ecualización");
        ecualizacionBoton.setFocusable(false);
        ecualizacionBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ecualizacionBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ecualizacionBoton.addActionListener(formListener);
        barraImagenesTB.add(ecualizacionBoton);

        umbralizacionSlider.setBackground(new java.awt.Color(204, 204, 204));
        umbralizacionSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        umbralizacionSlider.setToolTipText("Nivel de umbralización");
        umbralizacionSlider.setMaximumSize(new java.awt.Dimension(29, 100));
        umbralizacionSlider.setPreferredSize(new java.awt.Dimension(29, 80));
        umbralizacionSlider.addChangeListener(formListener);
        umbralizacionSlider.addFocusListener(formListener);
        barraImagenesTB.add(umbralizacionSlider);
        barraImagenesTB.add(jSeparator8);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/zoomin.png"))); // NOI18N
        jButton1.setToolTipText("Zoom in");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(formListener);
        barraImagenesTB.add(jButton1);

        disminuirBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/zoomout.png"))); // NOI18N
        disminuirBoton.setToolTipText("Zoom out");
        disminuirBoton.setFocusable(false);
        disminuirBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disminuirBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        disminuirBoton.addActionListener(formListener);
        barraImagenesTB.add(disminuirBoton);
        barraImagenesTB.add(jSeparator9);

        rot90Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotacion90.png"))); // NOI18N
        rot90Boton.setToolTipText("Rotación 90º");
        rot90Boton.setFocusable(false);
        rot90Boton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rot90Boton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rot90Boton.addActionListener(formListener);
        barraImagenesTB.add(rot90Boton);

        rot180Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotacion180.png"))); // NOI18N
        rot180Boton.setToolTipText("Rotacion 180º");
        rot180Boton.setFocusable(false);
        rot180Boton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rot180Boton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rot180Boton.addActionListener(formListener);
        barraImagenesTB.add(rot180Boton);

        rot270Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotacion270.png"))); // NOI18N
        rot270Boton.setToolTipText("Rotación 270º");
        rot270Boton.setFocusable(false);
        rot270Boton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rot270Boton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraImagenesTB.add(rot270Boton);

        giroLibreSlider.setBackground(new java.awt.Color(204, 204, 204));
        giroLibreSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        giroLibreSlider.setToolTipText("Giro libre");
        giroLibreSlider.setMaximumSize(new java.awt.Dimension(29, 100));
        giroLibreSlider.setPreferredSize(new java.awt.Dimension(29, 80));
        barraImagenesTB.add(giroLibreSlider);
        barraImagenesTB.add(jSeparator10);

        duplicarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/duplicar.png"))); // NOI18N
        duplicarBoton.setToolTipText("Duplicar");
        duplicarBoton.setFocusable(false);
        duplicarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        duplicarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        duplicarBoton.addActionListener(formListener);
        barraImagenesTB.add(duplicarBoton);

        negativoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/negativo.png"))); // NOI18N
        negativoBoton.setToolTipText("Negativo");
        negativoBoton.setFocusable(false);
        negativoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        negativoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        negativoBoton.addActionListener(formListener);
        barraImagenesTB.add(negativoBoton);

        relieveBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/relieve.png"))); // NOI18N
        relieveBoton.setToolTipText("Filtro de relieve");
        relieveBoton.setFocusable(false);
        relieveBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        relieveBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        relieveBoton.addActionListener(formListener);
        barraImagenesTB.add(relieveBoton);

        emborronamientoBoton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/emborronamiento.png"))); // NOI18N
        emborronamientoBoton2.setToolTipText("Filtro emborronamiento");
        emborronamientoBoton2.setFocusable(false);
        emborronamientoBoton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        emborronamientoBoton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        emborronamientoBoton2.addActionListener(formListener);
        barraImagenesTB.add(emborronamientoBoton2);

        enfoqueBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/enfoque.png"))); // NOI18N
        enfoqueBoton.setToolTipText("Filtro de enfoque");
        enfoqueBoton.setFocusable(false);
        enfoqueBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enfoqueBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        enfoqueBoton.addActionListener(formListener);
        barraImagenesTB.add(enfoqueBoton);

        bandasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevos/bandas.png"))); // NOI18N
        bandasBoton.setToolTipText("Extracción de Bandas");
        bandasBoton.setFocusable(false);
        bandasBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bandasBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bandasBoton.addActionListener(formListener);
        barraImagenesTB.add(bandasBoton);

        espacioColorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RGB", "YCC", "GREY" }));
        espacioColorCB.setToolTipText("Espacio de color");
        espacioColorCB.addActionListener(formListener);
        barraImagenesTB.add(espacioColorCB);

        disenioPropioBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sepia.png"))); // NOI18N
        disenioPropioBoton.setToolTipText("Operacion diseño propio 1");
        disenioPropioBoton.setFocusable(false);
        disenioPropioBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disenioPropioBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        disenioPropioBoton.addActionListener(formListener);
        barraImagenesTB.add(disenioPropioBoton);

        disenioPropio2Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sepia.png"))); // NOI18N
        disenioPropio2Boton.setToolTipText("Operación diseño propio 2");
        disenioPropio2Boton.setFocusable(false);
        disenioPropio2Boton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disenioPropio2Boton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        disenioPropio2Boton.addActionListener(formListener);
        barraImagenesTB.add(disenioPropio2Boton);

        getContentPane().add(barraImagenesTB, java.awt.BorderLayout.LINE_START);

        barraEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barraEstado.setMaximumSize(new java.awt.Dimension(20, 30));
        barraEstado.setMinimumSize(new java.awt.Dimension(20, 30));
        barraEstado.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout barraEstadoLayout = new javax.swing.GroupLayout(barraEstado);
        barraEstado.setLayout(barraEstadoLayout);
        barraEstadoLayout.setHorizontalGroup(
            barraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pixelLabel)
                .addContainerGap(1458, Short.MAX_VALUE))
        );
        barraEstadoLayout.setVerticalGroup(
            barraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pixelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(barraEstado, java.awt.BorderLayout.PAGE_END);

        jToolBar1.setBorder(null);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(100, 30));
        jToolBar1.setMinimumSize(new java.awt.Dimension(100, 30));
        jToolBar1.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(jToolBar1, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setViewportView(jTextPane1);

        escritorio.add(jScrollPane1);

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        archivoMenuBar.setText("Archivo");

        nuevoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        nuevoMenuItem.setText("Nuevo");
        nuevoMenuItem.addActionListener(formListener);
        archivoMenuBar.add(nuevoMenuItem);

        abrirMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/abrir.png"))); // NOI18N
        abrirMenuItem.setText("Abrir");
        abrirMenuItem.addActionListener(formListener);
        archivoMenuBar.add(abrirMenuItem);

        guardarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        guardarMenuItem.setText("Guardar");
        guardarMenuItem.addActionListener(formListener);
        archivoMenuBar.add(guardarMenuItem);

        menuBar.add(archivoMenuBar);

        verMenuBar.setText("Ver");

        verBarraEstadoCB.setSelected(true);
        verBarraEstadoCB.setText("Ver barra de estado");
        verBarraEstadoCB.addActionListener(formListener);
        verMenuBar.add(verBarraEstadoCB);

        verBarraFormasCB.setSelected(true);
        verBarraFormasCB.setText("Ver barra de formas");
        verBarraFormasCB.addActionListener(formListener);
        verMenuBar.add(verBarraFormasCB);

        verBarraImagenCB.setSelected(true);
        verBarraImagenCB.setText("Ver barra de imagen");
        verBarraImagenCB.addActionListener(formListener);
        verMenuBar.add(verBarraImagenCB);

        menuBar.add(verMenuBar);

        ayudaMenuBar.setText("Ayuda");

        acercaMenuItem.setText("Acerca de");
        acercaMenuItem.addActionListener(formListener);
        ayudaMenuBar.add(acercaMenuItem);

        menuBar.add(ayudaMenuBar);

        setJMenuBar(menuBar);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == lineaBoton) {
                VentanaPrincipal.this.lineaBotonActionPerformed(evt);
            }
            else if (evt.getSource() == rectanguloBoton) {
                VentanaPrincipal.this.rectanguloBotonActionPerformed(evt);
            }
            else if (evt.getSource() == elipseBoton) {
                VentanaPrincipal.this.elipseBotonActionPerformed(evt);
            }
            else if (evt.getSource() == colorTrazoCB) {
                VentanaPrincipal.this.colorTrazoCBActionPerformed(evt);
            }
            else if (evt.getSource() == rellenarBoton) {
                VentanaPrincipal.this.rellenarBotonActionPerformed(evt);
            }
            else if (evt.getSource() == colorRellenoCB) {
                VentanaPrincipal.this.colorRellenoCBActionPerformed(evt);
            }
            else if (evt.getSource() == tipoDegradadoCB) {
                VentanaPrincipal.this.tipoDegradadoCBActionPerformed(evt);
            }
            else if (evt.getSource() == degradado1CB) {
                VentanaPrincipal.this.degradado1CBActionPerformed(evt);
            }
            else if (evt.getSource() == degradado2CB) {
                VentanaPrincipal.this.degradado2CBActionPerformed(evt);
            }
            else if (evt.getSource() == transparenciaBoton) {
                VentanaPrincipal.this.transparenciaBotonActionPerformed(evt);
            }
            else if (evt.getSource() == tipoLineaCB) {
                VentanaPrincipal.this.tipoLineaCBActionPerformed(evt);
            }
            else if (evt.getSource() == alisarBoton) {
                VentanaPrincipal.this.alisarBotonActionPerformed(evt);
            }
            else if (evt.getSource() == recordSonidoBoton) {
                VentanaPrincipal.this.recordSonidoBotonActionPerformed(evt);
            }
            else if (evt.getSource() == pausaGrabacionBoton) {
                VentanaPrincipal.this.pausaGrabacionBotonActionPerformed(evt);
            }
            else if (evt.getSource() == stopRecordBoton) {
                VentanaPrincipal.this.stopRecordBotonActionPerformed(evt);
            }
            else if (evt.getSource() == reproducirSonidoBoton) {
                VentanaPrincipal.this.reproducirSonidoBotonActionPerformed(evt);
            }
            else if (evt.getSource() == pausaSonidoBoton) {
                VentanaPrincipal.this.pausaSonidoBotonActionPerformed(evt);
            }
            else if (evt.getSource() == stopSonidoBoton) {
                VentanaPrincipal.this.stopSonidoBotonActionPerformed(evt);
            }
            else if (evt.getSource() == contrasteBoton) {
                VentanaPrincipal.this.contrasteBotonActionPerformed(evt);
            }
            else if (evt.getSource() == iluminarBoton) {
                VentanaPrincipal.this.iluminarBotonActionPerformed(evt);
            }
            else if (evt.getSource() == oscurecerBoton) {
                VentanaPrincipal.this.oscurecerBotonActionPerformed(evt);
            }
            else if (evt.getSource() == sepiaBoton) {
                VentanaPrincipal.this.sepiaBotonActionPerformed(evt);
            }
            else if (evt.getSource() == tintarBoton) {
                VentanaPrincipal.this.tintarBotonActionPerformed(evt);
            }
            else if (evt.getSource() == colorTintadoCB) {
                VentanaPrincipal.this.colorTintadoCBActionPerformed(evt);
            }
            else if (evt.getSource() == ecualizacionBoton) {
                VentanaPrincipal.this.ecualizacionBotonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                VentanaPrincipal.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == disminuirBoton) {
                VentanaPrincipal.this.disminuirBotonActionPerformed(evt);
            }
            else if (evt.getSource() == rot90Boton) {
                VentanaPrincipal.this.rot90BotonActionPerformed(evt);
            }
            else if (evt.getSource() == rot180Boton) {
                VentanaPrincipal.this.rot180BotonActionPerformed(evt);
            }
            else if (evt.getSource() == duplicarBoton) {
                VentanaPrincipal.this.duplicarBotonActionPerformed(evt);
            }
            else if (evt.getSource() == negativoBoton) {
                VentanaPrincipal.this.negativoBotonActionPerformed(evt);
            }
            else if (evt.getSource() == relieveBoton) {
                VentanaPrincipal.this.relieveBotonActionPerformed(evt);
            }
            else if (evt.getSource() == emborronamientoBoton2) {
                VentanaPrincipal.this.emborronamientoBoton2ActionPerformed(evt);
            }
            else if (evt.getSource() == enfoqueBoton) {
                VentanaPrincipal.this.enfoqueBotonActionPerformed(evt);
            }
            else if (evt.getSource() == bandasBoton) {
                VentanaPrincipal.this.bandasBotonActionPerformed(evt);
            }
            else if (evt.getSource() == espacioColorCB) {
                VentanaPrincipal.this.espacioColorCBActionPerformed(evt);
            }
            else if (evt.getSource() == nuevoMenuItem) {
                VentanaPrincipal.this.nuevoMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == abrirMenuItem) {
                VentanaPrincipal.this.abrirMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == guardarMenuItem) {
                VentanaPrincipal.this.guardarMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == verBarraEstadoCB) {
                VentanaPrincipal.this.verBarraEstadoCBActionPerformed(evt);
            }
            else if (evt.getSource() == verBarraFormasCB) {
                VentanaPrincipal.this.verBarraFormasCBActionPerformed(evt);
            }
            else if (evt.getSource() == verBarraImagenCB) {
                VentanaPrincipal.this.verBarraImagenCBActionPerformed(evt);
            }
            else if (evt.getSource() == acercaMenuItem) {
                VentanaPrincipal.this.acercaMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == disenioPropioBoton) {
                VentanaPrincipal.this.disenioPropioBotonActionPerformed(evt);
            }
            else if (evt.getSource() == disenioPropio2Boton) {
                VentanaPrincipal.this.disenioPropio2BotonActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == brilloSlider) {
                VentanaPrincipal.this.brilloSliderFocusGained(evt);
            }
            else if (evt.getSource() == tintadoSlider) {
                VentanaPrincipal.this.tintadoSliderFocusGained(evt);
            }
            else if (evt.getSource() == umbralizacionSlider) {
                VentanaPrincipal.this.umbralizacionSliderFocusGained(evt);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == brilloSlider) {
                VentanaPrincipal.this.brilloSliderFocusLost(evt);
            }
            else if (evt.getSource() == tintadoSlider) {
                VentanaPrincipal.this.tintadoSliderFocusLost(evt);
            }
            else if (evt.getSource() == umbralizacionSlider) {
                VentanaPrincipal.this.umbralizacionSliderFocusLost(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == transparenciaSlider) {
                VentanaPrincipal.this.transparenciaSliderStateChanged(evt);
            }
            else if (evt.getSource() == grosorSpinner) {
                VentanaPrincipal.this.grosorSpinnerStateChanged(evt);
            }
            else if (evt.getSource() == brilloSlider) {
                VentanaPrincipal.this.brilloSliderStateChanged(evt);
            }
            else if (evt.getSource() == tintadoSlider) {
                VentanaPrincipal.this.tintadoSliderStateChanged(evt);
            }
            else if (evt.getSource() == umbralizacionSlider) {
                VentanaPrincipal.this.umbralizacionSliderStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarColores(javax.swing.JComboBox<Color> cb){
        cb.addItem(Color.BLACK);
        cb.addItem(Color.RED);
        cb.addItem(Color.BLUE);
        cb.addItem(Color.GREEN);
        cb.addItem(Color.WHITE);
        cb.addItem(Color.YELLOW);
        cb.setRenderer(new ColorRenderer());
    }
    
    private void inicializarRelleno(javax.swing.JComboBox<TipoRelleno> cb){
        cb.addItem(TipoRelleno.LISO);
        cb.addItem(TipoRelleno.DEGRADADO_HORIZONTAL);
        cb.addItem(TipoRelleno.DEGRADADO_VERTICAL);
        cb.addItem(TipoRelleno.DEGRADADO_DIAGONAL);
        cb.setRenderer(new RellenoRenderer());
    }
    
    private void inicializarTipoLinea(javax.swing.JComboBox<TipoLinea> cb){
        tipoLineaCB.addItem(TipoLinea.CONTINUA);
        tipoLineaCB.addItem(TipoLinea.DISCONTINUA);
        tipoLineaCB.addItem(TipoLinea.PUNTEADA);
        cb.setRenderer(new TipoLineaRenderer());
    }
    
    private void nuevoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuItemActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        
        BufferedImage img;
        String hS = JOptionPane.showInputDialog(null, "Introduzca altura de la imagen", "300");
        int h = new Integer(hS);
        String wS = JOptionPane.showInputDialog(null, "Introduzca ancho de la imagen", "300");
        int w = new Integer(wS);

        vi.getLienzo().setDimension(new Dimension(w,h));
        vi.getLienzo().setArea();
        vi.setTitle("Nueva");
        vi.setVisible(true);
    }//GEN-LAST:event_nuevoMenuItemActionPerformed

    private void guardarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuItemActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showSaveDialog(this);
            if(resp == JFileChooser.APPROVE_OPTION){
                try{
                    BufferedImage img = vi.getLienzo().getImage(true);
                    if(img!=null){
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    }
                }catch(Exception ex){
                    System.err.println("Error al guardar la imagen.");
                }
            }
        }
    }//GEN-LAST:event_guardarMenuItemActionPerformed

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        JFileChooser dlg = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Archivos de imagen", ImageIO.getReaderFormatNames());
        FileNameExtensionFilter soundFilter = new FileNameExtensionFilter("Archivos de sonido", "wav", "au");
        FileNameExtensionFilter videoFilter = new FileNameExtensionFilter("Archivos de video", "wav", "au");
        dlg.setFileFilter(imageFilter);
        dlg.setFileFilter(soundFilter);
        dlg.setFileFilter(videoFilter);
        
        int resp = dlg.showOpenDialog(this);
        if(resp == JFileChooser.APPROVE_OPTION){
            try{
                File f = dlg.getSelectedFile();
                if(imageFilter.accept(f)){//si es imagen
                    BufferedImage img = ImageIO.read(f);
                    VentanaInterna vi = new VentanaInterna();
                    vi.getLienzo().setImage(img);
                    this.escritorio.add(vi);
                    vi.setTitle(f.getName());
                    vi.setVisible(true);
                    int w = img.getWidth();
                    int h = img.getHeight();
                    vi.getLienzo().setDimension(new Dimension(w,h));
                }
                if(soundFilter.accept(f)){
                    
                }
                if(videoFilter.accept(f)){
                    
                }
            }catch(Exception ex){
                System.err.println("Error al leer el archivo.");
            }
        }
    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void acercaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaMenuItemActionPerformed
        String mensaje = "Paint\n05/07/2019 1.1\nMontserrat Rodríguez Zamorano";
        JOptionPane.showMessageDialog(null, mensaje, "Acerca de", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_acercaMenuItemActionPerformed

    private void lineaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            vi.getLienzo().setForma(Forma.LINEA);
        }
    }//GEN-LAST:event_lineaBotonActionPerformed

    private void rectanguloBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            vi.getLienzo().setForma(Forma.RECTANGULO);
        }
    }//GEN-LAST:event_rectanguloBotonActionPerformed

    private void elipseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            vi.getLienzo().setForma(Forma.OVALO);
        }
    }//GEN-LAST:event_elipseBotonActionPerformed

    private void rellenarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenarBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            Lienzo l = vi.getLienzo();
            l.setRellenoActivated(!vi.getLienzo().getRellenoActivated());
            if(!vi.getLienzo().getRellenoActivated()){
                vi.getLienzo().setRelleno(null);
            }
        }
    }//GEN-LAST:event_rellenarBotonActionPerformed

    private void transparenciaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            Lienzo l = vi.getLienzo();
            //si la transparencia está activada
            if(l.getTransparenciaActivated()){
                l.setTransparenciaActivated(false);
                transparenciaSlider.setEnabled(false);
            }
            else{//si no está activada
                l.setTransparenciaActivated(true);
                transparenciaSlider.setEnabled(true);
            }
        }
    }//GEN-LAST:event_transparenciaBotonActionPerformed

    private void alisarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisarBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            Lienzo l = vi.getLienzo();
            //si el alisado está activado
            l.changeAlisadoActivated();
        }
    }//GEN-LAST:event_alisarBotonActionPerformed

    private void recordSonidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordSonidoBotonActionPerformed
        try {
            temp = File.createTempFile("audioTemporal","wav");
        } catch (IOException ex) {
            System.err.println("Error al crear el archivo temporal");
        }
        grabando = true;
        recorder = new SMSoundRecorder(temp);
        recorder.record();
    }//GEN-LAST:event_recordSonidoBotonActionPerformed

    private void reproducirSonidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirSonidoBotonActionPerformed
        File f = (File) listaAudiosCB.getSelectedItem();
        if(f!=null){
            player = new SMClipPlayer(f);
            if(player!=null){
                player.play();
            }
        }
    }//GEN-LAST:event_reproducirSonidoBotonActionPerformed

    private void stopRecordBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopRecordBotonActionPerformed
        recorder.stop();
        grabando = false;
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if(resp == JFileChooser.APPROVE_OPTION){
            try{
                File f = dlg.getSelectedFile();
                Files.copy(temp.toPath(), f.toPath());
                listaAudiosCB.addItem(f);
                temp = null;
            }catch(Exception e){
                System.err.println("Error al guardar la grabación");
            }
        }
    }//GEN-LAST:event_stopRecordBotonActionPerformed

    private void colorTrazoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTrazoCBActionPerformed
        Color selectedColor = (Color) colorTrazoCB.getSelectedItem();
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            vi.getLienzo().setColorTrazo(selectedColor);
        }
    }//GEN-LAST:event_colorTrazoCBActionPerformed

    private void colorRellenoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorRellenoCBActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            if(vi.getLienzo().getRellenoActivated()){
                Color selectedColor = (Color) colorRellenoCB.getSelectedItem();
                vi.getLienzo().setColorRelleno(selectedColor);
            }
        }
    }//GEN-LAST:event_colorRellenoCBActionPerformed

    private void transparenciaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_transparenciaSliderStateChanged
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            float transp = (float) (this.transparenciaSlider.getValue()*0.01);
            vi.getLienzo().setTransparencia(transp);
        }
    }//GEN-LAST:event_transparenciaSliderStateChanged

    private void grosorSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_grosorSpinnerStateChanged
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            vi.getLienzo().setGrosor((int) this.grosorSpinner.getValue());
        }
    }//GEN-LAST:event_grosorSpinnerStateChanged

    private void pausaGrabacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaGrabacionBotonActionPerformed
        //si está grabando, pausar
        if(grabando){
            recorder.stop();
            grabando = false;
        }//en otro caso renaudar la grabacion
        else{
            recorder.record();
            grabando = true;
        }
    }//GEN-LAST:event_pausaGrabacionBotonActionPerformed

    private void stopSonidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSonidoBotonActionPerformed
        File f = (File) listaAudiosCB.getSelectedItem();
        if(f!=null){
            if(player!=null){
                player.stop();
            }
        }
    }//GEN-LAST:event_stopSonidoBotonActionPerformed

    private void pausaSonidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaSonidoBotonActionPerformed
        File f = (File) listaAudiosCB.getSelectedItem();
        if(f!=null){
            if(player!=null){
                player.pause();
            }
        }
    }//GEN-LAST:event_pausaSonidoBotonActionPerformed

    private void tipoDegradadoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDegradadoCBActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            if(vi.getLienzo().getRellenoActivated()){
                if(tipoDegradadoCB.getSelectedItem()==TipoRelleno.LISO){
                    Color selectedColor = (Color) colorRellenoCB.getSelectedItem();
                    vi.getLienzo().setColorRelleno(selectedColor);
                    vi.getLienzo().setTipoRelleno(TipoRelleno.LISO);
                }
                else if(tipoDegradadoCB.getSelectedItem()==TipoRelleno.DEGRADADO_HORIZONTAL){
                    vi.getLienzo().setTipoRelleno(TipoRelleno.DEGRADADO_HORIZONTAL);
                }
                else if(tipoDegradadoCB.getSelectedItem()==TipoRelleno.DEGRADADO_VERTICAL){
                    vi.getLienzo().setTipoRelleno(TipoRelleno.DEGRADADO_VERTICAL);
                }
                else if(tipoDegradadoCB.getSelectedItem()==TipoRelleno.DEGRADADO_DIAGONAL){
                    vi.getLienzo().setTipoRelleno(TipoRelleno.DEGRADADO_DIAGONAL);
                }
   
            }
            else{
                vi.getLienzo().setTipoRelleno(TipoRelleno.NINGUNO);
            }
        }
    }//GEN-LAST:event_tipoDegradadoCBActionPerformed

    private void degradado1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degradado1CBActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            Color selectedColor = (Color) degradado1CB.getSelectedItem();
            vi.getLienzo().setColorDeg1(selectedColor);
        }
    }//GEN-LAST:event_degradado1CBActionPerformed

    private void degradado2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degradado2CBActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            Color selectedColor = (Color) degradado2CB.getSelectedItem();
            vi.getLienzo().setColorDeg2(selectedColor);
        }
    }//GEN-LAST:event_degradado2CBActionPerformed

    private void tipoLineaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLineaCBActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            TipoLinea selectedTP = (TipoLinea) tipoLineaCB.getSelectedItem();
            vi.getLienzo().setStroke(selectedTP);
        }
    }//GEN-LAST:event_tipoLineaCBActionPerformed

    private void verBarraEstadoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraEstadoCBActionPerformed
         barraEstado.setVisible(!barraEstado.isVisible());
    }//GEN-LAST:event_verBarraEstadoCBActionPerformed

    private void verBarraFormasCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraFormasCBActionPerformed
        barraFormasTB.setVisible(!barraFormasTB.isVisible());
    }//GEN-LAST:event_verBarraFormasCBActionPerformed

    private void verBarraImagenCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraImagenCBActionPerformed
        barraImagenesTB.setVisible(!barraImagenesTB.isVisible());
    }//GEN-LAST:event_verBarraImagenCBActionPerformed

    private void brilloSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brilloSliderStateChanged
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        float nivelBrillo = (float) this.brilloSlider.getValue();
        if(vi != null){
            if(imgSource != null){
                try{
                    RescaleOp rop = new RescaleOp(1+(nivelBrillo/100), 0.0F, null);
                    BufferedImage imgdest = rop.filter(imgSource, null);
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_brilloSliderStateChanged

    private void brilloSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brilloSliderFocusGained
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            ColorModel cm = vi.getLienzo().getImage(true).getColorModel();
            WritableRaster raster = vi.getLienzo().getImage(true).copyData(null);
            boolean alfaPre = vi.getLienzo().getImage(true).isAlphaPremultiplied();
            imgSource = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_brilloSliderFocusGained

    private void brilloSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brilloSliderFocusLost
        imgSource = null;
    }//GEN-LAST:event_brilloSliderFocusLost

    private void tintarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintarBotonActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            LienzoImagen l = vi.getLienzo();
            //si la transparencia está activada
            if(l.getTintadoActivated()){
                l.setTintadoActivated(false);
                tintadoSlider.setEnabled(false);
            }
            else{//si no está activada
                l.setTintadoActivated(true);
                tintadoSlider.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tintarBotonActionPerformed

    private void colorTintadoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTintadoCBActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            Color selectedColor = (Color) colorTintadoCB.getSelectedItem();
            vi.getLienzo().setColorTintado(selectedColor);
        }
    }//GEN-LAST:event_colorTintadoCBActionPerformed

    private void tintadoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tintadoSliderStateChanged
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        float nivelTintado = (float) this.tintadoSlider.getValue();
        if(vi != null){
            if(imgSource != null){
                try{
                    TintOp tintado = new TintOp(vi.getLienzo().getColorTintado(), nivelTintado/100);
                    BufferedImage imgdest = tintado.filter(imgSource, null);
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_tintadoSliderStateChanged

    private void tintadoSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tintadoSliderFocusGained
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            ColorModel cm = vi.getLienzo().getImage(true).getColorModel();
            WritableRaster raster = vi.getLienzo().getImage(true).copyData(null);
            boolean alfaPre = vi.getLienzo().getImage(true).isAlphaPremultiplied();
            imgSource = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_tintadoSliderFocusGained

    private void tintadoSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tintadoSliderFocusLost
        imgSource = null;
    }//GEN-LAST:event_tintadoSliderFocusLost

    private void umbralizacionSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_umbralizacionSliderStateChanged
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        int umbral = (int) this.umbralizacionSlider.getValue();
        if(vi != null){
            if(imgSource != null){
                try{
                    UmbralizacionOp umbr = new UmbralizacionOp(umbral);
                    BufferedImage imgdest = umbr.filter(imgSource, null);
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_umbralizacionSliderStateChanged

    private void umbralizacionSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_umbralizacionSliderFocusGained
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            ColorModel cm = vi.getLienzo().getImage(true).getColorModel();
            WritableRaster raster = vi.getLienzo().getImage(true).copyData(null);
            boolean alfaPre = vi.getLienzo().getImage(true).isAlphaPremultiplied();
            imgSource = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_umbralizacionSliderFocusGained

    private void umbralizacionSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_umbralizacionSliderFocusLost
        imgSource = null;
    }//GEN-LAST:event_umbralizacionSliderFocusLost

    private void negativoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativoBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    int type = LookupTableProducer.TYPE_NEGATIVE;
                    LookupTable lt = LookupTableProducer.createLookupTable(type);
                    LookupOp lop = new LookupOp(lt, null);
                    //Imagen origen y destino iguales
                    lop.filter(imgSource, imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.out.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_negativoBotonActionPerformed

    private void relieveBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relieveBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    Kernel k = KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);
                    ConvolveOp cop = new ConvolveOp(k, ConvolveOp.EDGE_NO_OP, null);
                    imgSource = cop.filter(imgSource, null);
                    vi.getLienzo().setImage(imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.out.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_relieveBotonActionPerformed

    private void emborronamientoBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emborronamientoBoton2ActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    Kernel k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                    ConvolveOp cop = new ConvolveOp(k, ConvolveOp.EDGE_NO_OP, null);
                    imgSource = cop.filter(imgSource, null);
                    vi.getLienzo().setImage(imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.out.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_emborronamientoBoton2ActionPerformed

    private void enfoqueBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfoqueBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    Kernel k = KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);
                    ConvolveOp cop = new ConvolveOp(k, ConvolveOp.EDGE_NO_OP, null);
                    imgSource = cop.filter(imgSource, null);
                    vi.getLienzo().setImage(imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.out.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_enfoqueBotonActionPerformed

    private void contrasteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasteBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                try{
                    int type = LookupTableProducer.TYPE_SFUNCION;
                    LookupTable lt = LookupTableProducer.createLookupTable(type);
                    LookupOp lop = new LookupOp(lt, null);
                    //imagen origen y destino iguales
                    lop.filter(imgSource, imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_contrasteBotonActionPerformed

    private void iluminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iluminarBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    int type = LookupTableProducer.TYPE_LOGARITHM;
                    LookupTable lt = LookupTableProducer.createLookupTable(type);
                    LookupOp lop = new LookupOp(lt, null);
                    //Imagen origen y destino iguales
                    lop.filter(imgSource, imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_iluminarBotonActionPerformed

    private void oscurecerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oscurecerBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    int type = LookupTableProducer.TYPE_POWER;
                    LookupTable lt = LookupTableProducer.createLookupTable(type);
                    LookupOp lop = new LookupOp(lt, null);
                    //Imagen origen y destino iguales
                    lop.filter(imgSource, imgSource);
                    vi.repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_oscurecerBotonActionPerformed

    private void sepiaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepiaBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                SepiaOp sepia = new SepiaOp();
                sepia.filter(imgSource, imgSource);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_sepiaBotonActionPerformed

    private void duplicarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicarBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                //añadir nueva ventana interna
                int w = imgSource.getWidth();
                int h = imgSource.getHeight();
                
                VentanaInterna newVi = new VentanaInterna();
                newVi.getLienzo().setDimension(new Dimension(w,h));
                newVi.getLienzo().setImage(imgSource);
                newVi.setTitle(vi.getTitle()+" copia");
                escritorio.add(newVi);
                newVi.setVisible(true);
            }
        }
    }//GEN-LAST:event_duplicarBotonActionPerformed

    private void rot90BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rot90BotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                try{
                    double r = Math.toRadians(90);
                    //se rota en el punto medio de la imagen
                    int temp0 = imgSource.getWidth()/2;
                    int temp1 = imgSource.getHeight()/2;
                    Point p = new Point(temp0, temp1);
                    AffineTransform ar = AffineTransform.getRotateInstance(r, p.x,p.y);
                    
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(ar, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(imgSource, null);
                    
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_rot90BotonActionPerformed

    private void rot180BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rot180BotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rot180BotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                try{
                    AffineTransform at = AffineTransform.getScaleInstance(1.25, 1.25);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(imgSource, null);
                    
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void disminuirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                try{
                    AffineTransform at = AffineTransform.getScaleInstance(0.75, 0.75);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(imgSource, null);
                    
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                }catch(Exception e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_disminuirBotonActionPerformed

    private void ecualizacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecualizacionBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
           imgSource = vi.getLienzo().getImage(true);
           if(imgSource != null){
               try{
                   EqualizationOp ecualizacion = new EqualizationOp();
                   ecualizacion.filter(imgSource, imgSource);
                   vi.getLienzo().setImage(imgSource);
                   vi.getLienzo().repaint();
               }catch(Exception e){
                   System.err.println(e.getLocalizedMessage());
               }
           }
        }
    }//GEN-LAST:event_ecualizacionBotonActionPerformed

    private void bandasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandasBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                //Creamos el modelo de color de la nueva image basado
                //en un espacio de color GRAY
                ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                ComponentColorModel cm = new ComponentColorModel(cs, false, false, Transparency.OPAQUE, DataBuffer.TYPE_BYTE);
                //Crear una imagen por cada banda
                int numBandas = imgSource.getRaster().getNumBands();
                for(int iBanda = 0; iBanda < numBandas; iBanda++){
                    //Creamos el nuevo raster a partir del raster de la imagen original
                    int bandList[] = {iBanda};
                    WritableRaster bandRaster = (WritableRaster) imgSource.getRaster().createWritableChild(0,
                    0, imgSource.getWidth(), imgSource.getHeight(), 0, 0, bandList);
                    //Create una nueva imagen que contiene como raster el
                    //correspondiente a la banda
                    BufferedImage imgBanda = new BufferedImage(cm, bandRaster, false, null);
                    
                    //añadir nueva ventana interna
                    VentanaInterna newVi = new VentanaInterna();
                    escritorio.add(newVi);
                    newVi.setVisible(true);
                    newVi.getLienzo().setImage(imgBanda);
                    newVi.setTitle("banda" + (iBanda+1));
                    //guardar dimension
                    int w = imgBanda.getWidth();
                    int h = imgBanda.getHeight();
                    newVi.getLienzo().setDimension(new Dimension(w,h));
                }
            }
        }
    }//GEN-LAST:event_bandasBotonActionPerformed

    private void espacioColorCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioColorCBActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                String itemSelec = (String) espacioColorCB.getSelectedItem();
                ColorSpace cs = null;
                if("RGB".equals(itemSelec)){
                    cs = ColorSpace.getInstance(ColorSpace.CS_LINEAR_RGB);
                }
                else if("YCC".equals(itemSelec)){
                    cs = ColorSpace.getInstance(ColorSpace.CS_PYCC);
                }
                else if("GREY".equals(itemSelec)){
                    cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                }
                //comprobamos si el espacio de partida es RGB
                if(imgSource.getColorModel().getColorSpace().isCS_sRGB()){
                    ColorConvertOp cop = new ColorConvertOp(cs, null);
                    BufferedImage imgOut = cop.filter(imgSource, null);
                    
                    //añadir nueva ventana interna
                    VentanaInterna newVi = new VentanaInterna();
                    escritorio.add(newVi);
                    newVi.setVisible(true);
                    newVi.getLienzo().setImage(imgOut);
                    newVi.setTitle("["+itemSelec.toString()+"]");
                    //guardar dimension
                    int w = imgOut.getWidth();
                    int h = imgOut.getHeight();
                    newVi.getLienzo().setDimension(new Dimension(w,h));
                }
            }
        }
    }//GEN-LAST:event_espacioColorCBActionPerformed

    private void disenioPropioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disenioPropioBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                disenioPropioOp dp = new disenioPropioOp();
                dp.filter(imgSource, imgSource);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_disenioPropioBotonActionPerformed

    private void disenioPropio2BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disenioPropio2BotonActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if(vi != null){
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource != null){
                disenioPropio2Op dp = new disenioPropio2Op();
                dp.filter(imgSource, imgSource);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_disenioPropio2BotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Figura> FigurasCB;
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JMenuItem acercaMenuItem;
    private javax.swing.JToggleButton alisarBoton;
    private javax.swing.JMenu archivoMenuBar;
    private javax.swing.JMenu ayudaMenuBar;
    private javax.swing.JButton bandasBoton;
    private javax.swing.JPanel barraEstado;
    private javax.swing.JToolBar barraFormasTB;
    private javax.swing.JToolBar barraImagenesTB;
    private javax.swing.JSlider brilloSlider;
    private javax.swing.JComboBox<Color> colorRellenoCB;
    private javax.swing.JComboBox<Color> colorTintadoCB;
    private javax.swing.JComboBox<Color> colorTrazoCB;
    private javax.swing.JButton contrasteBoton;
    private javax.swing.JComboBox<Color> degradado1CB;
    private javax.swing.JComboBox<Color> degradado2CB;
    private javax.swing.JButton disenioPropio2Boton;
    private javax.swing.JButton disenioPropioBoton;
    private javax.swing.JButton disminuirBoton;
    private javax.swing.JButton duplicarBoton;
    private javax.swing.JButton ecualizacionBoton;
    private javax.swing.JToggleButton elipseBoton;
    private javax.swing.JButton emborronamientoBoton2;
    private javax.swing.JButton enfoqueBoton;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JComboBox<String> espacioColorCB;
    private javax.swing.ButtonGroup formasBG;
    private javax.swing.JSlider giroLibreSlider;
    private javax.swing.JSpinner grosorSpinner;
    private javax.swing.JMenuItem guardarMenuItem;
    private javax.swing.JButton iluminarBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton lineaBoton;
    private javax.swing.JComboBox<File> listaAudiosCB;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton negativoBoton;
    private javax.swing.JMenuItem nuevoMenuItem;
    private javax.swing.JButton oscurecerBoton;
    private javax.swing.JToggleButton pausaGrabacionBoton;
    private javax.swing.JToggleButton pausaSonidoBoton;
    private javax.swing.JLabel pixelLabel;
    private javax.swing.JToggleButton recordSonidoBoton;
    private javax.swing.JToggleButton rectanguloBoton;
    private javax.swing.JButton relieveBoton;
    private javax.swing.JToggleButton rellenarBoton;
    private javax.swing.JToggleButton reproducirSonidoBoton;
    private javax.swing.JButton rot180Boton;
    private javax.swing.JButton rot270Boton;
    private javax.swing.JButton rot90Boton;
    private javax.swing.ButtonGroup rotacionBG;
    private javax.swing.JButton sepiaBoton;
    private javax.swing.ButtonGroup sonidoBG;
    private javax.swing.JToggleButton stopRecordBoton;
    private javax.swing.JToggleButton stopSonidoBoton;
    private javax.swing.JSlider tintadoSlider;
    private javax.swing.JToggleButton tintarBoton;
    private javax.swing.JComboBox<TipoRelleno> tipoDegradadoCB;
    private javax.swing.JComboBox<TipoLinea> tipoLineaCB;
    private javax.swing.JToggleButton transparenciaBoton;
    private javax.swing.JSlider transparenciaSlider;
    private javax.swing.JSlider umbralizacionSlider;
    private javax.swing.JCheckBoxMenuItem verBarraEstadoCB;
    private javax.swing.JCheckBoxMenuItem verBarraFormasCB;
    private javax.swing.JCheckBoxMenuItem verBarraImagenCB;
    private javax.swing.JMenu verMenuBar;
    // End of variables declaration//GEN-END:variables
}
