/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

import java.awt.Component;
import java.io.File;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;

/**
 * Ventana multimedia que permite reproducir vídeos.
 * @author Montserrat Rodríguez Zamorano
 * @version 1.1
 */
public class VentanaMultimediaJMFPlayer extends VentanaMultimedia {
    private Player player;
    /**
     * Crea la nueva forma VentanaInternaJMFPlayer
     * @param f
     */
    public VentanaMultimediaJMFPlayer(File f) {
        initComponents();
        String aFichero = "file:" + f.getAbsolutePath();
        MediaLocator ml = new MediaLocator(aFichero);
        try{
            player = Manager.createRealizedPlayer(ml);
            Component vc = player.getVisualComponent();
            if(vc!=null) add(vc, java.awt.BorderLayout.CENTER);
            Component cpc = player.getControlPanelComponent();
            if(cpc!=null)add(cpc, java.awt.BorderLayout.SOUTH);
            this.pack();
        }catch(Exception e){
            System.err.println("VentanaInternaJMFPlayer: " + e);
            player=null;
        }
    }
    
    public static VentanaMultimediaJMFPlayer getInstance(File f){
        VentanaMultimediaJMFPlayer v = new VentanaMultimediaJMFPlayer(f);
        return (v.player!=null?v:null);
    }
    /**
     * Reproduce el vídeo.
     */
    public void play(){
        if(player!=null){
            try{
                player.start();
            }catch(Exception e){
                System.err.println("VentanaInternaJMFPlayer: "+e);
            }
        }
    }
    /**
     * Detiene la reproducción del vídeo.
     */
    public void stop(){
        if(player!=null){
            try{
                player.stop();
            }catch(Exception e){
                System.err.println("VentanaInternaJMFPlayer: "+e);
            }
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setToolTipText("Ventana vídeo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
