/**
 *
 * @author Montserrat Rodríguez Zamorano
 * @version 14.06.2019
 */
package iu;

import java.awt.Dimension;
import java.awt.image.BufferedImage;

public class LienzoImagen extends Lienzo {
    private BufferedImage img;
    
    /**
     * Creates new form LienzoImagen
     */
    public LienzoImagen() {
        initComponents();
    }
    
    public void setImage(BufferedImage img){
        this.img = img;
        if(img!=null){
            setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
        }
    }
    
    public BufferedImage getImage(boolean drawVector){
        if(drawVector){
            //codigo para guardar también las formas
            BufferedImage imgDest = new BufferedImage(img.getWidth(), img.getHeight(), img.getType());
            this.paint(imgDest.createGraphics());
            img = imgDest;
        }
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
